#include "common.h"

const char* tokenTypeNames[] = {
    [TOKEN_NUMBER] = "TOKEN_NUMBER",
    [TOKEN_LEFT_PAREN] = "TOKEN_LEFT_PAREN",
    [TOKEN_RIGHT_PAREN] = "TOKEN_RIGHT_PAREN",
    [TOKEN_PLUS] = "TOKEN_PLUS",
    [TOKEN_MINUS] = "TOKEN_MINUS",
    [TOKEN_STAR] = "TOKEN_STAR",
    [TOKEN_SLASH] = "TOKEN_SLASH",
    [TOKEN_FACTORIAL] = "TOKEN_FACTORIAL",
    [TOKEN_EOF] = "TOKEN_EOF"
};
